[tool.black]
skip-string-normalization = false
skip-magic-trailing-comma = false
include = '\.pyi?$'

[tool.isort]
profile = "black"                 # black-compatible (e.g., trailing comma)
#known_first_party = ["relay"]     # use separate section for project sources
force_sort_within_sections = true # don't separate import vs from
order_by_type = false             # sort alphabetic regardless of case

