name: Developer Productivity project CI workflow
on:
  push:
    branches:
      - main
    tags:
      - '**'
  release:
    types:
      - published
  pull_request:

jobs:
  lint_and_test:
    name: lint and test
    uses: developerproductivity/logilica-weekly-report/.github/workflows/python_lint_and_test.yaml@main
    with:
      python_versions: ${{ vars.DEVELOPERPRODUCTIVITY_PYTHON_VERSIONS }}
