name: Developer Productivity project reusable Python lint and test workflow
on:
  workflow_call:
    inputs:
      python_versions:
        required: true
        type: string

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_versions) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
          # architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install \
              -r requirements.txt \
              -r tests/requirements.txt \
              -r .github/workflows/requirements.txt
      - name: Run python style and linting tools
        run: |
          err=0
          echo autoflake:
          autoflake --check-diff . || err=$?
          echo black:
          black --check . || err=$?
          echo docformatter:
          docformatter . || err=$?
          echo flake8:
          flake8 . || err=$?
          echo isort:
          isort --check . || err=$?
          exit $err
      - name: Run tests with coverage
        run: |
          pytest --timeout=300 \
              --cov-config pyproject.toml \
              --cov=logilica_cli --cov=tests \
              --cov-report=term --cov-report=html
      - name: Publish coverage report to job summary
        # publishing only once
        if: strategy.job-index == 0
        run: |
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage HTML artifact
        # uploading only once
        if: strategy.job-index == 0
        uses: actions/upload-artifact@v4
        with:
          name: Coverage for ${{ github.event.head_commit.id }}
          path: htmlcov
          if-no-files-found: error
