name: Developer Productivity project reusable Python lint and test workflow
on:
  workflow_call:
    inputs:
      python_versions:
        required: true
        type: string

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_versions) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
          # architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install -r src/requirements.txt -r tests/requirements.txt -r .github/workflows/requirements.txt
      - name: Run python style and linting tools
        run: |
          pip install autoflake black docformatter flake8 isort
          mll=88  # Maximum line length
          err=0
          echo autoflake:
          autoflake --check --remove-all-unused-imports --remove-unused-variables . || err=$?
          echo black:
          black --check --line-length $mll . || err=$?
          echo docformatter:
          docformatter --check --recursive --black --wrap-descriptions 79 --wrap-summaries 79 . || err=$?
          echo flake8:
          flake8 --max-line-length $mll . || err=$?
          echo isort:
          isort --check --profile black --line-length $mll . || err=$?
          exit $err
      - name: Run tests with coverage
        run: |
          pip install coverage
          # Run the unit tests
          python -m coverage run -a -m unittest discover -v tests
          # Generate the coverage HTML report
          python -m coverage html
      - name: Publish coverage report to job summary
        # publishing only once
        if: strategy.job-index == 0
        run: |
          pip install html2text
          html2text --ignore-images --ignore-links -b 0 htmlcov/index.html >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage HTML artifact
        # uploading only once
        if: strategy.job-index == 0
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
